services: 
  imagenfront:
    image: alepellereca/imagenfront:latest
    restart: always
    ports:
      - "3002:8080"  
    volumes: 
    - .:/opt

  imagenback:
    image: alepellereca/imagenback:latest
    restart: always
    ports:
    - "8081:8080"  
    volumes: 
    - .:/opt
